# New And Existing Users


Calculate the share of new and existing users for each month in the table. Output the month, share of new users, and share of existing users as a ratio.
New users are defined as users who started using services in the current month (there is no usage history in previous months). Existing users are users who used services in current month, but they also used services in any previous month.
Assume that the dates are all from the year 2020.

In [4]:
import pandas as pd
q=pd.read_csv('fact_events.csv')
q.time_id=q.time_id.apply(pd.to_datetime)
q=q.sort_values(by='time_id',ascending=True)
q

,id,time_id,user_id,customer_id,client_id,event_type,event_id
117,118,2020-02-01,6713-OKOMC,Electric Gravity,mobile,file received,2
108,109,2020-02-03,9237-HQITU,Sendit,mobile,video call started,6
27,28,2020-02-03,7795-CFOCW,Connectix,mobile,api message received,5
78,79,2020-02-03,7469-LKBCI,Zoomit,desktop,file received,2
79,80,2020-02-03,0280-XJGEX,eShop,desktop,message sent,3
...,...,...,...,...,...,...,...
40,41,2020-04-13,9959-WOFKT,Zoomit,mobile,video call received,7
142,143,2020-04-13,7469-LKBCI,Sendit,desktop,video call received,7
133,134,2020-04-16,9763-GRSKD,Connectix,desktop,message sent,3
44,45,2020-04-18,9959-WOFKT,Connectix,desktop,file received,2
9,10,2020-04-21,9763-GRSKD,Sendit,desktop,file received,2

In [5]:
q['month']=q.time_id.dt.month

In [13]:
u=q[~q.user_id.duplicated()].groupby('month').user_id.count().reset_index(name='new_user')

In [18]:
u['total_user']=u.new_user.cumsum()

In [20]:
u['existing_user']=u.total_user-u.new_user

In [24]:
u['new_share']=(u.new_user/u.total_user*100).round(2)

In [28]:
u['existing_share']=(u.existing_user/u.total_user*100).round(2)

In [29]:
u.iloc[:,[0,1,-2,3,-1]]

   month  new_user  new_share  existing_user  existing_share
0      2        13     100.00              0            0.00
1      3         5      27.78             13           72.22
2      4         2      10.00             18           90.00