# Distance Per Dollar
You’re given a dataset of uber rides with the traveling distance (‘distance_to_travel’) and cost (‘monetary_cost’) for each ride. For each date, find the difference between the distance-per-dollar for that date and the average distance-per-dollar for that year-month. Distance-per-dollar is defined as the distance traveled divided by the cost of the ride.


The output should include the year-month (YYYY-MM) and the absolute average difference in distance-per-dollar (Absolute value to be rounded to the 2nd decimal).
You should also count both success and failed request_status as the distance and cost values are populated for all ride requests. Also, assume that all dates are unique in the dataset. Order your results by earliest request date first.

In [1]:
import pandas as pd
import numpy as np
q=pd.read_csv('uber_request_logs.csv')

In [2]:
# change datatype of 'request_date' column
q.request_date=q.request_date.apply(pd.to_datetime)

In [3]:
# extract 'month' and 'year' from the date column
q['month']=q.request_date.dt.month
q['year']=q.request_date.dt.year

In [4]:
# apply the year-motnh (YYYY-MM) format
q.request_date=q.request_date.dt.strftime('%Y-%m')

In [5]:
# create the distance_per_dollar column
q['distance_per_dollar']=(q['distance_to_travel']/q['monetary_cost']).round(2)

In [6]:
# create the average distance per dollar by month
q['avg_month'] = q.groupby('month').transform('mean')['distance_per_dollar']

C:\Users\Admin\AppData\Local\Temp\ipykernel_27472\145431829.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  q['avg_month'] = q.groupby('month').transform('mean')['distance_per_dollar']

In [7]:
# create the average distance per dollar by year
q['avg_year'] = q.groupby(['year']).transform('mean')['distance_per_dollar']

C:\Users\Admin\AppData\Local\Temp\ipykernel_27472\3780962642.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  q['avg_year'] = q.groupby(['year']).transform('mean')['distance_per_dollar']

In [8]:
# remove the redudant columns
q.drop(columns=['request_status','distance_to_travel','monetary_cost','driver_to_client_distance','month','year'])
q=q.drop(columns=['request_status','distance_to_travel','monetary_cost','driver_to_client_distance','month','year'])

In [10]:
# find the distance diff with avg_month and avg_year
q['distance_vs_avg_month'] =abs(q['distance_per_dollar']-q['avg_month'])
q['distance_vs_avg_year'] =abs(q['distance_per_dollar']-q['avg_year'])
q.sort_values(by='request_date',ascending=False)

,request_id,request_date,distance_per_dollar,avg_month,avg_year,distance_vs_avg_month,distance_vs_avg_year
19,20,2020-10,2.34,2.805,5.9475,0.465,3.6075
18,19,2020-10,3.27,2.805,5.9475,0.465,2.6775
17,18,2020-09,0.13,1.950,5.9475,1.820,5.8175
16,17,2020-09,3.77,1.950,5.9475,1.820,2.1775
15,16,2020-08,25.27,13.655,5.9475,11.615,19.3225
14,15,2020-08,2.04,13.655,5.9475,11.615,3.9075
13,14,2020-07,4.88,2.855,5.9475,2.025,1.0675
12,13,2020-07,0.83,2.855,5.9475,2.025,5.1175
11,12,2020-06,2.41,7.380,5.9475,4.970,3.5375
10,11,2020-06,12.35,7.380,5.9475,4.970,6.4025
9,10,2020-05,1.14,7.580,5.9475,6.440,4.8075
8,9,2020-05,14.02,7.580,5.9475,6.440,8.0725
7,8,2020-04,4.31,3.120,5.9475,1.190,1.6375
6,7,2020-04,1.93,3.120,5.9475,1.190,4.0175
5,6,2020-03,9.74,6.610,5.9475,3.130,3.7925
4,5,2020-03,3.48,6.610,5.9475,3.130,2.4675
3,4,2020-02,7.66,6.080,5.9475,1.580,1.7125
2,3,2020-02,4.50,6.080,5.9475,1.580,1.4475
1,2,2020-01,4.12,7.440,5.9475,3.320,1.8275
0,1,2020-01,10.76,7.440,5.9475,3.320,4.8125