# Find all businesses whose lowest and highest inspection scores are different

Find all businesses whose lowest and highest inspection scores are different.
Output the corresponding business name and the lowest and highest scores of each business.
Order the result based on the business name in ascending order.

In [5]:
import pandas as pd
import numpy as np
q=pd.read_csv('sf_restaurant_health_violations.csv',encoding='latin-1')

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
0,5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.798,-122.403,"{'longitude': '-122.403154', 'needs_recoding':...",NaN,5800_20171017,10/17/2017,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or ...,Low Risk
1,64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.789,-122.412,"{'longitude': '-122.41188', 'needs_recoding': ...",NaN,64236_20170725,7/25/2017,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
2,1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.764,-122.508,"{'longitude': '-122.507779', 'needs_recoding':...",NaN,1991_20171129,11/29/2017,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk
3,3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.405845', 'needs_recoding':...",NaN,3816_20160728,7/28/2016,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk
4,39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.781,-122.464,"{'longitude': '-122.463762', 'needs_recoding':...",NaN,39119_20160718,7/18/2016,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015,86.0,Routine - Unscheduled,500_20150930_103154,Unclean or degraded floors walls or ceilings,Low Risk
293,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015,86.0,Routine - Unscheduled,500_20150930_103119,Inadequate and inaccessible handwashing facili...,Moderate Risk
294,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018,92.0,Routine - Unscheduled,500_20180403_103120,Moderate risk food holding temperature,Moderate Risk
295,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018,92.0,Routine - Unscheduled,500_20180403_103144,Unapproved or unmaintained equipment or utensils,Low Risk
296,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20161128,11/28/2016,89.0,Routine - Unscheduled,500_20161128_103105,Improper cooling methods,High Risk

In [21]:
# Fill the missing values of inspection score with zero
q.inspection_score=q.inspection_score.fillna(0)

In [22]:
# Create a highest inspection score of each bussinesses
q['highest_inspection_score']=q.groupby('business_name')['inspection_score'].transform(max)

In [23]:
# Create a lowest inspection score of each bussinesses
q['lowest_inspection_score']=q.groupby('business_name')['inspection_score'].transform(min)

In [25]:
# Find all businesses whose lowest and highest inspection scores are different.
q[q['highest_inspection_score']!=q['lowest_inspection_score']].iloc[:,[0,1,-1,-2]].sort_values(by='business_name',ascending=True)
q=q[q['highest_inspection_score']!=q['lowest_inspection_score']].iloc[:,[0,1,-1,-2]].sort_values(by='business_name',ascending=True)

,business_id,business_name,lowest_inspection_score,highest_inspection_score
74,83351,City Super,77.0,78.0
95,83351,City Super,77.0,78.0
264,89276,"Fresca Gardens, Inc",82.0,88.0
136,89276,"Fresca Gardens, Inc",82.0,88.0
8,68872,Jiang Ling Cuisine Restaurant,72.0,74.0
59,68872,Jiang Ling Cuisine Restaurant,72.0,74.0
254,86780,Peet's Coffee & Tea,0.0,96.0
26,86780,Peet's Coffee & Tea,0.0,96.0
162,86780,Peet's Coffee & Tea,0.0,96.0
177,83046,Project Juice,96.0,100.0
212,80302,Project Juice,96.0,100.0
288,500,Roxanne Cafe,86.0,92.0
291,500,Roxanne Cafe,86.0,92.0
290,500,Roxanne Cafe,86.0,92.0
292,500,Roxanne Cafe,86.0,92.0
293,500,Roxanne Cafe,86.0,92.0
294,500,Roxanne Cafe,86.0,92.0
289,500,Roxanne Cafe,86.0,92.0
287,500,Roxanne Cafe,86.0,92.0
296,500,Roxanne Cafe,86.0,92.0
295,500,Roxanne Cafe,86.0,92.0
58,7747,SAFEWAY STORE #964,0.0,81.0
14,7747,SAFEWAY STORE #964,0.0,81.0
271,64236,Sutter Pub and Restaurant,88.0,90.0
1,64236,Sutter Pub and Restaurant,88.0,90.0
128,90839,The Grove - Design District,0.0,96.0
79,90839,The Grove - Design District,0.0,96.0
115,38231,Wines of California Wine Bar,88.0,92.0
111,38231,Wines of California Wine Bar,88.0,92.0

In [28]:
# Find the unique values of table
q[~q.duplicated()]

,business_id,business_name,lowest_inspection_score,highest_inspection_score
74,83351,City Super,77.0,78.0
264,89276,"Fresca Gardens, Inc",82.0,88.0
8,68872,Jiang Ling Cuisine Restaurant,72.0,74.0
254,86780,Peet's Coffee & Tea,0.0,96.0
177,83046,Project Juice,96.0,100.0
212,80302,Project Juice,96.0,100.0
288,500,Roxanne Cafe,86.0,92.0
58,7747,SAFEWAY STORE #964,0.0,81.0
271,64236,Sutter Pub and Restaurant,88.0,90.0
128,90839,The Grove - Design District,0.0,96.0
115,38231,Wines of California Wine Bar,88.0,92.0