# Product Market Share



Write a query to find the Market Share at the Product Brand level for each Territory, for Time Period Q4-2021. Market Share is the number of Products of a certain Product Brand brand sold in a territory, divided by the total number of Products sold in this Territory.
Output the ID of the Territory, name of the Product Brand and the corresponding Market Share in percentages. Only include these Product Brands that had at least one sale in a given territory.

In [21]:
import pandas as pd
sales=pd.read_csv('fct_customer_sales.csv')
cus_ter=pd.read_csv('map_customer_territory.csv')
dim=pd.read_csv('dim_product.csv')
pd.set_option('display.max_row',500)
sales

   ust_id prod_sku_id       order_date  order_value order_id
0    C274        P474   6/28/2021 0:00         1500     O110
1    C285        P472   6/28/2021 0:00          899     O118
2    C282        P487   6/30/2021 0:00          500     O125
3    C282        P476    7/2/2021 0:00          999     O146
4    C284        P487    7/7/2021 0:00          500     O149
5    C285        P478   7/12/2021 0:00          700     O150
6    C287        P489   7/13/2021 0:00          189     O151
7    C284        P482   7/15/2021 0:00          725     O156
8    C281        P482   7/19/2021 0:00          725     O164
9    C282        P480   7/22/2021 0:00          300     O172
10   C281        P477   7/23/2021 0:00         1400     O174
11   C273        P487   7/26/2021 0:00          500     O181
12   C287        P482   7/27/2021 0:00          725     O186
13   C280        P482   7/30/2021 0:00          725     O190
14   C282        P482    8/9/2021 0:00          725     O202
15   C280        P475   8/10/2021 0:00         1200     O203
16   C285        P487   8/11/2021 0:00          500     O219
17   C282        P486   8/12/2021 0:00          420     O228
18   C285        P479   8/12/2021 0:00         1020     O242
19   C276        P477   8/13/2021 0:00         1400     O244
20   C283        P476   8/18/2021 0:00          999     O246
21   C285        P474   8/18/2021 0:00         1500     O275
22   C273        P482   8/19/2021 0:00          725     O276
23   C280        P474   8/19/2020 0:00         1500     O290
24   C277        P480   8/23/2021 0:00          300     O293
25   C284        P482   8/30/2021 0:00          725     O313
26   C287        P479   8/31/2021 0:00         1020     O315
27   C277        P484    9/8/2021 0:00          899     O322
28   C275        P479   9/10/2021 0:00         1020     O336
29   C275        P475   9/13/2021 0:00         1200     O337
30   C283        P482   9/13/2021 0:00          725     O368
31   C283        P486   9/14/2021 0:00          420     O371
32   C282        P482   9/20/2021 0:00          725     O381
33   C273        P487   9/23/2021 0:00          500     O385
34   C285        P472   10/1/2021 0:00          899     O398
35   C283        P475   10/4/2021 0:00         1200     O399
36   C279        P479   10/4/2021 0:00         1020     O423
37   C273        P472   10/6/2021 0:00          899     O430
38   C274        P476   10/6/2021 0:00          999     O438
39   C278        P478   10/8/2021 0:00          700     O445
40   C278        P472  10/11/2021 0:00          899     O487
41   C285        P486  10/12/2021 0:00          420     O500
42   C273        P487  10/15/2021 0:00          500     O513
43   C284        P489  10/18/2021 0:00          189     O518
44   C283        P486  10/19/2021 0:00          420     O523
45   C283        P477  10/22/2021 0:00         1400     O566
46   C284        P472  10/25/2021 0:00          899     O567
47   C277        P482  10/29/2021 0:00          725     O571
48   C280        P482   11/3/2021 0:00          725     O599
49   C278        P480   11/4/2021 0:00          300     O618
50   C277        P489   11/5/2021 0:00          189     O620
51   C281        P482   11/9/2021 0:00          725     O626
52   C283        P480  11/11/2021 0:00          300     O645
53   C284        P487  11/15/2021 0:00          500     O657
54   C275        P479  11/19/2021 0:00         1020     O680
55   C281        P479  11/22/2021 0:00         1020     O681
56   C285        P480  11/22/2021 0:00          300     O713
57   C284        P476  11/23/2021 0:00          999     O728
58   C274        P485  11/24/2011 0:00          629     O745
59   C286        P474  11/25/2021 0:00         1500     O747
60   C286        P484  11/26/2021 0:00          899     O752
61   C277        P472  11/29/2021 0:00          899     O776
62   C281        P484  11/30/2021 0:00          899     O788
63   C275        P474   12/1/2021 0:00         1500     O796
64   C280        P475   12/3/2021 0:00         1200     O831
65   C285        P480  12/10/2021 0:00          300     O834
66   C286        P487  12/13/2021 0:00          500     O835
67   C281        P476  12/15/2021 0:00          999     O844
68   C284        P486  12/15/2021 0:00          420     O853
69   C283        P478  12/16/2021 0:00          700     O858
70   C285        P489  12/16/2021 0:00          189     O881
71   C285        P484  12/20/2021 0:00          899     O887
72   C286        P489  12/20/2021 0:00          189     O893
73   C287        P485  12/24/2021 0:00          629     O906
74   C280        P477  12/24/2021 0:00         1400     O922
75   C276        P478  12/31/2021 0:00          700     O951
76   C283        P486    1/3/2022 0:00          420     O963
77   C281        P489   1/11/2022 0:00          189     O991

In [8]:
sales['order_date']=pd.to_datetime(sales.order_date)

In [15]:
q4_2021_sales=sales[(sales.order_date.dt.quarter==4)&(sales.order_date.dt.year==2021)]
q4_2021_sales

   ust_id prod_sku_id order_date  order_value order_id
34   C285        P472 2021-10-01          899     O398
35   C283        P475 2021-10-04         1200     O399
36   C279        P479 2021-10-04         1020     O423
37   C273        P472 2021-10-06          899     O430
38   C274        P476 2021-10-06          999     O438
39   C278        P478 2021-10-08          700     O445
40   C278        P472 2021-10-11          899     O487
41   C285        P486 2021-10-12          420     O500
42   C273        P487 2021-10-15          500     O513
43   C284        P489 2021-10-18          189     O518
44   C283        P486 2021-10-19          420     O523
45   C283        P477 2021-10-22         1400     O566
46   C284        P472 2021-10-25          899     O567
47   C277        P482 2021-10-29          725     O571
48   C280        P482 2021-11-03          725     O599
49   C278        P480 2021-11-04          300     O618
50   C277        P489 2021-11-05          189     O620
51   C281        P482 2021-11-09          725     O626
52   C283        P480 2021-11-11          300     O645
53   C284        P487 2021-11-15          500     O657
54   C275        P479 2021-11-19         1020     O680
55   C281        P479 2021-11-22         1020     O681
56   C285        P480 2021-11-22          300     O713
57   C284        P476 2021-11-23          999     O728
59   C286        P474 2021-11-25         1500     O747
60   C286        P484 2021-11-26          899     O752
61   C277        P472 2021-11-29          899     O776
62   C281        P484 2021-11-30          899     O788
63   C275        P474 2021-12-01         1500     O796
64   C280        P475 2021-12-03         1200     O831
65   C285        P480 2021-12-10          300     O834
66   C286        P487 2021-12-13          500     O835
67   C281        P476 2021-12-15          999     O844
68   C284        P486 2021-12-15          420     O853
69   C283        P478 2021-12-16          700     O858
70   C285        P489 2021-12-16          189     O881
71   C285        P484 2021-12-20          899     O887
72   C286        P489 2021-12-20          189     O893
73   C287        P485 2021-12-24          629     O906
74   C280        P477 2021-12-24         1400     O922
75   C276        P478 2021-12-31          700     O951

In [22]:
q=pd.merge(q4_2021_sales,cus_ter,left_on='ust_id',right_on='cust_id').merge(dim)
q

,ust_id,prod_sku_id,order_date,order_value,order_id,cust_id,territory_id,prod_sku_name,prod_brand,market_name
0,C285,P472,2021-10-01,899,O398,C285,T5,iphone-13,Apple,Apple IPhone 13
1,C273,P472,2021-10-06,899,O430,C273,T3,iphone-13,Apple,Apple IPhone 13
2,C278,P472,2021-10-11,899,O487,C278,T2,iphone-13,Apple,Apple IPhone 13
3,C284,P472,2021-10-25,899,O567,C284,T5,iphone-13,Apple,Apple IPhone 13
4,C277,P472,2021-11-29,899,O776,C277,T1,iphone-13,Apple,Apple IPhone 13
5,C285,P486,2021-10-12,420,O500,C285,T5,hero-10,GoPro,GoPro Hero 10
6,C283,P486,2021-10-19,420,O523,C283,T4,hero-10,GoPro,GoPro Hero 10
7,C284,P486,2021-12-15,420,O853,C284,T5,hero-10,GoPro,GoPro Hero 10
8,C285,P480,2021-11-22,300,O713,C285,T5,galaxy-watch4,Samsung,Samsung Galaxy Watch4
9,C285,P480,2021-12-10,300,O834,C285,T5,galaxy-watch4,Samsung,Samsung Galaxy Watch4
10,C283,P480,2021-11-11,300,O645,C283,T4,galaxy-watch4,Samsung,Samsung Galaxy Watch4
11,C278,P480,2021-11-04,300,O618,C278,T2,galaxy-watch4,Samsung,Samsung Galaxy Watch4
12,C285,P489,2021-12-16,189,O881,C285,T5,tuner-xl,JBL,JBL Tuner
13,C284,P489,2021-10-18,189,O518,C284,T5,tuner-xl,JBL,JBL Tuner
14,C277,P489,2021-11-05,189,O620,C277,T1,tuner-xl,JBL,JBL Tuner
15,C286,P489,2021-12-20,189,O893,C286,T3,tuner-xl,JBL,JBL Tuner
16,C285,P484,2021-12-20,899,O887,C285,T5,inspiron-13,Dell,Dell Inspiron 13
17,C281,P484,2021-11-30,899,O788,C281,T4,inspiron-13,Dell,Dell Inspiron 13
18,C286,P484,2021-11-26,899,O752,C286,T3,inspiron-13,Dell,Dell Inspiron 13
19,C283,P475,2021-10-04,1200,O399,C283,T4,macbook-air-13,Apple,Apple Makbook Air 13''
20,C280,P475,2021-12-03,1200,O831,C280,T4,macbook-air-13,Apple,Apple Makbook Air 13''
21,C283,P477,2021-10-22,1400,O566,C283,T4,ipad-pro,Apple,Apple IPad Pro
22,C280,P477,2021-12-24,1400,O922,C280,T4,ipad-pro,Apple,Apple IPad Pro
23,C283,P478,2021-12-16,700,O858,C283,T4,galaxy-s21,Samsung,Samsung Galaxy S21
24,C278,P478,2021-10-08,700,O445,C278,T2,galaxy-s21,Samsung,Samsung Galaxy S21
25,C276,P478,2021-12-31,700,O951,C276,T1,galaxy-s21,Samsung,Samsung Galaxy S21
26,C279,P479,2021-10-04,1020,O423,C279,T2,galaxy-s22plus,Samsung,Samsung Galaxy S22+
27,C281,P479,2021-11-22,1020,O681,C281,T4,galaxy-s22plus,Samsung,Samsung Galaxy S22+
28,C275,P479,2021-11-19,1020,O680,C275,T1,galaxy-s22plus,Samsung,Samsung Galaxy S22+
29,C273,P487,2021-10-15,500,O513,C273,T3,max,GoPro,GoPro Max
30,C284,P487,2021-11-15,500,O657,C284,T5,max,GoPro,GoPro Max
31,C286,P487,2021-12-13,500,O835,C286,T3,max,GoPro,GoPro Max
32,C274,P476,2021-10-06,999,O438,C274,T3,ipad,Apple,Apple IPad
33,C284,P476,2021-11-23,999,O728,C284,T5,ipad,Apple,Apple IPad
34,C281,P476,2021-12-15,999,O844,C281,T4,ipad,Apple,Apple IPad
35,C277,P482,2021-10-29,725,O571,C277,T1,galaxy-tab-s8,Samsung,Samsung Galaxy Tab 8
36,C280,P482,2021-11-03,725,O599,C280,T4,galaxy-tab-s8,Samsung,Samsung Galaxy Tab 8
37,C281,P482,2021-11-09,725,O626,C281,T4,galaxy-tab-s8,Samsung,Samsung Galaxy Tab 8
38,C275,P474,2021-12-01,1500,O796,C275,T1,macbook-pro-13,Apple,Apple Macbook Pro 13''
39,C286,P474,2021-11-25,1500,O747,C286,T3,macbook-pro-13,Apple,Apple Macbook Pro 13''
40,C287,P485,2021-12-24,629,O906,C287,T3,powershot-g7,Canon,Canon PowerShot G7 X Mark III

Write a query to find the Market Share at the Product Brand level for each Territory, for Time Period Q4-2021. Market Share is the number of Products of a certain Product Brand brand sold in a territory, divided by the total number of Products sold in this Territory. Output the ID of the Territory, name of the Product Brand and the corresponding Market Share in percentages. Only include these Product Brands that had at least one sale in a given territory.

In [34]:
q1=q.groupby(['prod_brand','territory_id']).order_value.sum().reset_index(name='total_orders')
q1

   prod_brand territory_id  total_orders
0       Apple           T1          2399
1       Apple           T2           899
2       Apple           T3          3398
3       Apple           T4          6199
4       Apple           T5          2797
5       Canon           T3           629
6        Dell           T3           899
7        Dell           T4           899
8        Dell           T5           899
9       GoPro           T3          1000
10      GoPro           T4           420
11      GoPro           T5          1340
12        JBL           T1           189
13        JBL           T3           189
14        JBL           T5           378
15    Samsung           T1          2445
16    Samsung           T2          2020
17    Samsung           T4          3470
18    Samsung           T5           600

In [35]:
q2=q.groupby('prod_brand').order_value.sum().reset_index(name='total_orders')
q2

  prod_brand  total_orders
0      Apple         15692
1      Canon           629
2       Dell          2697
3      GoPro          2760
4        JBL           756
5    Samsung          8535

In [40]:
q3=q1.merge(q2,on='prod_brand').rename(columns={'total_orders_x':'total_order_per_ter','total_orders_y':'total_order_per_brand'})
q3

   prod_brand territory_id  total_order_per_ter  total_order_per_brand
0       Apple           T1                 2399                  15692
1       Apple           T2                  899                  15692
2       Apple           T3                 3398                  15692
3       Apple           T4                 6199                  15692
4       Apple           T5                 2797                  15692
5       Canon           T3                  629                    629
6        Dell           T3                  899                   2697
7        Dell           T4                  899                   2697
8        Dell           T5                  899                   2697
9       GoPro           T3                 1000                   2760
10      GoPro           T4                  420                   2760
11      GoPro           T5                 1340                   2760
12        JBL           T1                  189                    756
13        JBL           T3                  189                    756
14        JBL           T5                  378                    756
15    Samsung           T1                 2445                   8535
16    Samsung           T2                 2020                   8535
17    Samsung           T4                 3470                   8535
18    Samsung           T5                  600                   8535

In [44]:
q3['percentage']=(q3.total_order_per_ter/q3.total_order_per_brand*100).round()
q3

,prod_brand,territory_id,total_order_per_ter,total_order_per_brand,percentage
0,Apple,T1,2399,15692,15.0
1,Apple,T2,899,15692,6.0
2,Apple,T3,3398,15692,22.0
3,Apple,T4,6199,15692,40.0
4,Apple,T5,2797,15692,18.0
5,Canon,T3,629,629,100.0
6,Dell,T3,899,2697,33.0
7,Dell,T4,899,2697,33.0
8,Dell,T5,899,2697,33.0
9,GoPro,T3,1000,2760,36.0
10,GoPro,T4,420,2760,15.0
11,GoPro,T5,1340,2760,49.0
12,JBL,T1,189,756,25.0
13,JBL,T3,189,756,25.0
14,JBL,T5,378,756,50.0
15,Samsung,T1,2445,8535,29.0
16,Samsung,T2,2020,8535,24.0
17,Samsung,T4,3470,8535,41.0
18,Samsung,T5,600,8535,7.0