# Find the first and last inspection dates for vermin infestations per municipality

Find the first and last inspections for vermin infestations per municipality.
Output the result along with the business postal code.

In [34]:
import pandas as pd
import numpy as np
q=pd.read_csv('sf_restaurant_health_violations.csv',encoding='latin-1')
q

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
0,5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.798,-122.403,"{'longitude': '-122.403154', 'needs_recoding':...",NaN,5800_20171017,10/17/2017 0:00,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or ...,Low Risk
1,64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.789,-122.412,"{'longitude': '-122.41188', 'needs_recoding': ...",NaN,64236_20170725,7/25/2017 0:00,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
2,1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.764,-122.508,"{'longitude': '-122.507779', 'needs_recoding':...",NaN,1991_20171129,11/29/2017 0:00,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk
3,3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.405845', 'needs_recoding':...",NaN,3816_20160728,7/28/2016 0:00,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk
4,39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.781,-122.464,"{'longitude': '-122.463762', 'needs_recoding':...",NaN,39119_20160718,7/18/2016 0:00,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015 0:00,86.0,Routine - Unscheduled,500_20150930_103154,Unclean or degraded floors walls or ceilings,Low Risk
293,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015 0:00,86.0,Routine - Unscheduled,500_20150930_103119,Inadequate and inaccessible handwashing facili...,Moderate Risk
294,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018 0:00,92.0,Routine - Unscheduled,500_20180403_103120,Moderate risk food holding temperature,Moderate Risk
295,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018 0:00,92.0,Routine - Unscheduled,500_20180403_103144,Unapproved or unmaintained equipment or utensils,Low Risk
296,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20161128,11/28/2016 0:00,89.0,Routine - Unscheduled,500_20161128_103105,Improper cooling methods,High Risk

In [35]:
# change the data type into datetime
q.inspection_date=q.inspection_date.apply(pd.to_datetime)

In [36]:
# find the violation which contain 'vermin'
q=q[q.violation_description.str.contains('vermin',na=False)].iloc[:,[5,-6]]
q

     business_postal_code inspection_date
6                 94118.0      2016-10-17
30                94102.0      2018-03-28
66                94108.0      2016-01-07
123               94110.0      2017-11-27
136               94103.0      2018-01-17
172               94112.0      2016-09-07
177               94102.0      2017-10-19
183               94118.0      2016-11-14
189               94110.0      2018-05-09
197               94103.0      2017-07-24
202               94114.0      2017-09-27
209               94114.0      2018-06-05
215               94102.0      2016-07-20
218               94133.0      2017-05-23
233               94110.0      2016-05-02
252               94115.0      2016-09-19
261               94111.0      2017-09-26
264               94103.0      2017-05-05
286               94118.0      2016-09-07

In [37]:
# rank the inspection date of each business postal code in ascending order
q['first_inspection_date']=q.groupby('business_postal_code').inspection_date.rank()

In [38]:
# rank the inspection date of each business postal code in descending order
q['last_inspection_date']=q.groupby('business_postal_code').inspection_date.rank(ascending=False)

In [51]:
# find the first inspection date of each business postal codes
first_inspection_date=q[(q.first_inspection_date==1)].drop(columns=['first_inspection_date','last_inspection_date'])

In [52]:
# find the last inspection date of each business postal codes
last_inspection_date=q[(q.last_inspection_date==1)].drop(columns=['first_inspection_date','last_inspection_date'])

In [55]:
# merge 2 aboved tables together:
pd.merge(first_inspection_date,last_inspection_date,on='business_postal_code').rename(columns={
    'inspection_date_x':'first_inspection_date','inspection_date_y':'last_inspection_date'})

   business_postal_code first_inspection_date last_inspection_date
0               94108.0            2016-01-07           2016-01-07
1               94112.0            2016-09-07           2016-09-07
2               94114.0            2017-09-27           2018-06-05
3               94102.0            2016-07-20           2018-03-28
4               94133.0            2017-05-23           2017-05-23
5               94110.0            2016-05-02           2018-05-09
6               94115.0            2016-09-19           2016-09-19
7               94111.0            2017-09-26           2017-09-26
8               94103.0            2017-05-05           2018-01-17
9               94118.0            2016-09-07           2016-11-14